version: '3'
services:
  app:
    build:  .
    volumes:
      - .:/app
    container_name: app
    restart: always
    ports:
      - "3000:3000"
    command: bash -c "/app/start.sh"
    env_file: .env
